### ISSUE TITLE
Nothing shows on map

### ISSUE THREAD

**Issue by ILoveZerg** [OpenPoGo/OpenPoGoWeb#141]
127.0.0.1 - - [31/Jul/2016 02:41:17] code 404, message File not found

I recieve this error constantly. It shows over and over. The map loads and says data is loaded but no routes or anything are displayed.

**Comment by BobbyWibowo** [comment]
Where did you see that error? Did you start the map with SimpleHTTPServer? Can you open your browser's dev console and post the error messages in that instead?

**Comment by aleixab** [comment]
Go to PokemonGo-Bot/pokemongo_bot/stepper.py
Line 112 - remove if and indent properly
Line 123 - remove if and indent properly
The problem is that is checking for the file and it has not been created.

Other solution is to manually create the .json file but the problem will persist for other accounts.

**Comment by ILoveZerg** [comment]
```
GET 
XHR 
http://localhost:8080/socket.io/ [HTTP/1.0 404 File not found 0ms]
GET 
XHR 
http://localhost:8080/socket.io/ [HTTP/1.0 404 File not found 5ms]
GET 
XHR 
http://localhost:8080/location-(redacted)@gmail.com.json [HTTP/1.0 404 File not found 1ms]
GET 
XHR 
http://localhost:8080/catchable-(redacted)@gmail.com.json [HTTP/1.0 404 File not found 0ms]

```

These get repeated over and over. I Looked at stepper.py but there are no if statements on line 112 or 123 or  anything to do with those files. I am starting the map with the command: sudo python -m SimpleHTTPServer 8080. I added in location/catchable/inventory json files and it removed all the errors except socket.io but it still displays nothing.

**Comment by aleixab** [comment]
Which bot are you using? OpenPoGoBot or PokemonGo-Bot?
My solution was for PokemonGo-Bot. OpenPoGoBot has been updated and map has been disabled =s.

**Comment by ILoveZerg** [comment]
Well that would make sense lol. Do you have a link to PokemonGo-Bot. R/PokemonDev removed all the links to the bots.

**Comment by BobbyWibowo** [comment]
This is PokemonGo-Bot: https://github.com/PokemonGoF/PokemonGo-Bot
If you're still having issue with the map even with that bot, try my fork of OpenPoGoWeb: https://github.com/BobbyWibowo/OpenPoGoWeb. I mostly customized this to work well with PokemonGo-Bot (to be honest, I haven't tried using it with OpenPoGoBot, and I highly doubt it'll work well together).

**Comment by ILoveZerg** [comment]
Thanks for your help. I will give that a shot.

**Comment by ILoveZerg** [comment]
Hey Bobby, I got pokemonGo-bot running succefully. I am trying to use your map.  If I run it with simpleHTTPServer I recieve errors about not finding the 3 json files. Which are in the web directory. However, it is trying to find location-YOUR-USERNAME.json. Is my username loaded from the userdata.js file?

**Comment by BobbyWibowo** [comment]
@ILoveZerg Yes, you need to update the userdata.js file. Please follow the config example in userdata.js.example file. After you finish that, it should be working just fine.

**Comment by ILoveZerg** [comment]
Thanks, I changed the displayname and not the username. It is mostly working now. By that I mean the map is working and showing route/pokestops/pokemon. However all of the buttons on the right open my items. I am seeing these two errors in the console:

`16:38:17.499 Unhandled rejection getNameById@http://localhost:8080/web/js/Pokemon.js:39:12
Pokedex@http://localhost:8080/web/js/Pokedex.js:8:23
updateInventory@http://localhost:8080/web/js/Player.js:27:20
mapView.addInventory/a<@http://localhost:8080/web/js/main.js:271:9
r@http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:31:7720
[22]</e.exports/i.prototype._settlePromiseFromHandler@http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:13039
[22]</e.exports/i.prototype._settlePromise@http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:13842
[22]</e.exports/i.prototype._settlePromise0@http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:14543
[22]</e.exports/i.prototype._settlePromises@http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:15873
[2]</r.prototype._drainQueue@http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:29:3146
[2]</r.prototype._drainQueues@http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:29:3204
r/this.drainQueues@http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:29:1236
1 bluebird.min.js:29:21134
`

`16:38:17.479 Unhandled rejection n.parseJSON@http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js:4:16639
Xb@http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js:4:18959
y@http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js:4:22405
.send/c@http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js:4:26925
1 bluebird.min.js:29:21134
`

**Comment by BobbyWibowo** [comment]
> Thanks, I changed the displayname and not the username.

Er, you need to fill both. The display name feature was simply for appearance sake (much like the display name thingy in the app), while the username will be used get the correct JSON files.

By the way, I'm guessing we should move this discussion to my fork instead. Considering that we're now talking about issues regarding my fork instead of this.

**Comment by ILoveZerg** [comment]
Yah I have both changed now. I just did not see the username the first time around. Thanks for all your help. Ill try and work through these errors I'm getting.

**Comment by Miamony** [comment]
i cant see logs or my bots on the map onmly a rnd european area
and i got this error

Unhandled rejection TypeError: Cannot read property 'length' of undefined
    at Object.trainerFunc (http://127.0.0.1:8000/js/main.js:790:35)
    at http://127.0.0.1:8000/js/main.js:553:14
    at r (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:31:7722)
    at i._settlePromiseFromHandler (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:13044)
    at i._settlePromise (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:13847)
    at i._settlePromise0 (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:14548)
    at i._settlePromises (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:15878)
    at r._drainQueue (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:29:3148)
    at r._drainQueues (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:29:3209)
    at drainQueues (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:29:1238)
bluebird.min.js:29 Unhandled rejection TypeError: Cannot read property 'candy' of undefined
    at filterInventory (http://127.0.0.1:8000/js/Player.js:18:39)
    at Player.updateInventory (http://127.0.0.1:8000/js/Player.js:25:21)
    at http://127.0.0.1:8000/js/main.js:281:33
    at r (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:31:7722)
    at i._settlePromiseFromHandler (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:13044)
    at i._settlePromise (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:13847)
    at i._settlePromise0 (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:14548)
    at i._settlePromises (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:15878)
    at r._drainQueue (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:29:3148)
    at r._drainQueues (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:29:3209)
    at drainQueues (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:29:1238)
5bluebird.min.js:29 Unhandled rejection TypeError: Cannot read property 'length' of undefined
    at Object.trainerFunc (http://127.0.0.1:8000/js/main.js:790:35)
    at http://127.0.0.1:8000/js/main.js:553:14
    at r (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:31:7722)
    at i._settlePromiseFromHandler (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:13044)
    at i._settlePromise (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:13847)
    at i._settlePromise0 (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:14548)
    at i._settlePromises (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:15878)
    at r._drainQueue (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:29:3148)
    at r._drainQueues (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:29:3209)
    at drainQueues (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:29:1238)
bluebird.min.js:29 Unhandled rejection TypeError: Cannot read property 'candy' of undefined
    at filterInventory (http://127.0.0.1:8000/js/Player.js:18:39)
    at Player.updateInventory (http://127.0.0.1:8000/js/Player.js:25:21)
    at http://127.0.0.1:8000/js/main.js:281:33
    at r (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:31:7722)
    at i._settlePromiseFromHandler (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:13044)
    at i._settlePromise (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:13847)
    at i._settlePromise0 (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:14548)
    at i._settlePromises (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:30:15878)
    at r._drainQueue (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:29:3148)
    at r._drainQueues (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:29:3209)
    at drainQueues (http://cdn.jsdelivr.net/bluebird/3.4.1/bluebird.min.js:29:1238)

**Comment by BobbyWibowo** [comment]
userdata.js?

**Comment by Miamony** [comment]
// MUST CONFIGURE THE USERS ARRAY AND GOOGLE MAPS API KEY.
// YOU CAN GET A KEY HERE: https://developers.google.com/maps/documentation/javascript/get-api-key
var userInfo = {
    users: {
        /*
         \* 'displayName' is merely for appearance sake, you still need to fill in your username in the "YOUR_USERNAME" or "YOUR_OTHER_USERNAME" area (optional)
         \* 'colors > botPath' will be used to color the bot's path in the map (mandatory)
         \* 'colors > primary' will be used as the primary color for buttons in the bot menu and experience bar in the trainer info submenu (mandatory)
         \* 'colors > secondary' will be used as the secondary color for buttons in the bot menu and experience bar in the trainer info submenu (mandatory)
         \* 'icon > path' is the path to the trainer icon which will be used as the bot's marker in the map (mandatory)
         \* 'icon > width' is the desired width of the trainer icon, if not defined or the value is lower than 0, the original size will be used (optional)
         \* 'icon > height' is the desired height of the trainer icon, if not defined or the value is lower than 0, the original size will be used (optional)
         \* 'focus' will define whether the bot should be focused in the first load, this will only be used when there are more than 1 user (optional)
         */

```
    "xxxxxxx": {
        //displayName: "xxxxx",
        colors: {
            botPath: "#2471a3",
            primary: "#2471a3",
            secondary: "#a9cce3"
        },
        icon: {
            path: "image/trainer/pokeball.png",
            width: 36,
            height: 36
        },
        focus: true
    },
    /*"YOUR_OTHER_USERNAME": {
        //displayName: "YOUR_OTHER_DISPLAYNAME",
        colors: {
            botPath: "#a93226",
            primary: "#a93226",
            secondary: "#e6b0aa"
        },
        icon: {
            path: "image/trainer/m46.png",
            width: -1,
            height: -1
        }
    },
    "YOUR_OTHER_USERNAME": {
        //displayName: "YOUR_OTHER_DISPLAYNAME",
        colors: {
            botPath: "#884eA0",
            primary: "#884eA0",
            secondary: "#d7bde2"
        },
        icon: {
            path: "image/trainer/f87.png",
            width: -1,
            height: -1
        }
    },*/
},
collapseBotMenu: true,
userZoom: true,
zoom: 16,
userFollow: true,
botPath: true,
defaultMapStyle: "pokemongo",
gMapsAPIKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```

**Comment by BobbyWibowo** [comment]
Did you use the latest commit? Honestly I can't guess much from those error logs. I can only assume that the JSON files didn't have enough data as expected.

```
bluebird.min.js:29 Unhandled rejection TypeError: Cannot read property 'candy' of undefined
at filterInventory (http://127.0.0.1:8000/js/Player.js:18:39)
at Player.updateInventory (http://127.0.0.1:8000/js/Player.js:25:21)
at http://127.0.0.1:8000/js/main.js:281:33
```

This means that 'inventory_item_data' didn't exist since it'd try reading 'candy' property from that object. But that's strange. It should have existed if the bot were working properly (the others errors should have been merely a chain reaction). Which bot were you using?
And are you sure that the account you used on the bot weren't really "fresh"? I mean, you had actually tried playing the game once with that account and had at least finished the tutorial. The last time I checked, you have to finish the tutorial on the game, otherwise there'd be some issues with your inventory while using the web interface (I haven't really confirmed).

**Comment by Miamony** [comment]
im using your wchill/refactor branch
and yes i already played the tutorial
but can you give me a git pull command for always download the wchill/refactor newest stuff ?

**Comment by BobbyWibowo** [comment]
Should be just as simple as doing `git pull https://github.com/BobbyWibowo/OpenPoGoWeb` since that branch is already the default branch on my forked repo

**Comment by Miamony** [comment]
i get error 
error: Your local changes to the following files would be overwritten by merge:
        .gitignore
        README.md
        config/userdata.js.example
        css/main.css
        index.html
        js/main.js
Please commit your changes or stash them before you can merge.
error: The following untracked working tree files would be overwritten by merge:
        js/Item.js
        js/Logger.js
        js/Player.js
        js/Pokedex.js
        js/Pokemon.js

**Comment by BobbyWibowo** [comment]
Do `git stash`, then do the git pull again. After that, copy userdata.js.example then name it as userdata.js (this is the one that you have to edit).

**Comment by JohnAxae** [comment]
@BobbyWibowo I've tried your map multiple times over the last days.
With dev and master version of PokemonGo-Bot and I always get these errors:

![Errors](http://image.prntscr.com/image/de746314a37045aab16b7573034f1b2d.png)

**Comment by BobbyWibowo** [comment]
@JohnAxae First error means that `inventory_item_data` doesn't exist in your `inventory-YOUR_USERNAME.json` file (that thing is an array which contains information of literally all of your character's Pokemon, items, stats, Pokedex, etc.). Second error means `cells` information doesn't exist in your `location-YOUR_USERNAME.json` file (that thing is an array which contains information of all existing PokeStops, Gyms, any maybe something else).  You need to confirm whether those two files are indeed being updated by the bot. Please note that those files aren't immediately updated after you start the bot. It may take a few seconds. Also, please try the latest commit: https://github.com/BobbyWibowo/OpenPoGoWeb/commit/13b5bb62d50b1fd5f6a661edc4cd1328808ec8c9. I had made a few failsafes.

**Comment by JohnAxae** [comment]
@BobbyWibowo still nothing, all the json-files are constantly up to date, and the inventory_item_data and cells exists though, and I get those failsafe errors also.

![prove image](http://image.prntscr.com/image/4a7519b61bb84bba8378d7ca68ee2933.png)

**Comment by BobbyWibowo** [comment]
@JohnAxae At first I thought it had something to do with the new PokemonGo-Map Synergy commit (which I didn't have prior to pushing my latest commit), but after updating to the latest commit of PokemonGo-Bot's dev branch, it was still working just fine. Oh well, for now I'm quite lost as well. Anyway, I'm currently working into integrating the new nearby Pokemon feature (which includes rewriting lots of things as well), so let's see whether it'll work with that version later.
