### ISSUE TITLE
Bot crashes when formating the name of PokeStop with special unicode chars

### ISSUE THREAD

**Issue by ghost** [OpenPoGo/OpenPoGoWeb#174]
Just made a pull at 11:45 am to confirm that its still an issue.

my system: 
Ubuntu 14.04.4 LTS

traceback:
[2016-08-03 11:56:59] [Navigation] Arrived at PokeStop "Die Fette Raupe" (0.26km away)
Traceback (most recent call last):
  File "pokecli.py", line 347, in <module>
    main()
  File "pokecli.py", line 340, in main
    bot.run()
  File "/home/smoky/OpenPoGoBot/pokemongo_bot/**init**.py", line 96, in run
    for destination in self.navigator.navigate(map_cells):
  File "/home/smoky/OpenPoGoBot/pokemongo_bot/navigation/fort_navigator.py", line 34, in navigate
    yield Destination(fort.latitude, fort.longitude, 0.0, name="PokeStop \"{}\"".format(fort_name))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 2: ordinal not in range(128)

thanks for the great work though

**Comment by ghost** [comment]
I think i got a solution.

Now the bot continues at the same step:
[2016-08-03 13:00:22] [Navigation] Arrived at PokeStop "Die Fette Raupe" (0.26km away)
[2016-08-03 13:00:25] [Navigation] Walking towards PokeStop "Gr**ü**ne Wasserpumpe" (0.41km away, eta 3.00 minutes)

my solution (from http://stackoverflow.com/questions/5760936/handle-wrongly-encoded-character-in-python-unicode-string)

add this lines to the beginning of the file OpenPoGoBot/pokemongo_bot/navigation/fort_navigator.py

```
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

**Comment by BobbyWibowo** [comment]
Shouldn't this posted in the [OpenPoGoBot repo](https://github.com/OpenPoGo/OpenPoGoBot)? I mean, this repo is for the web viewer.

**Comment by ghost** [comment]
Ohh.. yea..

my bad. sorry ^^

**Comment by wchill** [comment]
Fixed in OpenPoGoBot PR 159.
