### ISSUE TITLE
Can't get map to work?

### ISSUE THREAD

**Issue by flopk** [OpenPoGo/OpenPoGoWeb#175]
I'm managing to keep up with some of the coding here but I am very new to all this. I'm using PokemonGoBot Dev branch. I get this error when trying to run the server
127.0.0.1 - - [03/Aug/2016 11:24:02] code 404, message File not found
127.0.0.1 - - [03/Aug/2016 11:24:02] "GET /location-**wrongname**.json?v=1470219842724 H                                                                      TTP/1.1" 404 -
The .json files it is looking for are my screen name despite the userdata.js file having my correct login. I have changed this to the correct username (google) but it still reverts to that.

Also where it says in the instructions to navigate:

> $ cd OpenPoGoBot\web  
> $ python -m SimpleHTTPServer

I don't have a \web folder here. Am I meant to run this from the web folder in PokemonGoBot? (I have tried this and still get same error message) Gaaaaaaa
What am I missing?

**Comment by powerpatch** [comment]
I've tried following the instructions from start to finish about 50 times now and I can't get this to work no matter what I do.
I've managed to get a large number of bots going and even configured so they show in the logs (with log patch).

But nothing is making them show up or any of the nifty features I'm reading about.
![map](https://cloud.githubusercontent.com/assets/2665152/17365114/22784a0a-5939-11e6-86a7-59b7da345279.png)

![chromeconsole](https://cloud.githubusercontent.com/assets/2665152/17365083/fad85e40-5938-11e6-88a3-7f9207a5fede.png)

**Comment by IcicleTF** [comment]
I've mostly gotten it to work, but right when the bot starts up, I receive this: Traceback (most recent call last):
  File "D:\Github\PokemonGo-Bot\pokecli.py", line 446, in <module>
    main()
  File "D:\Github\PokemonGo-Bot\pokecli.py", line 71, in main
    bot.tick()
  File "D:\Github\PokemonGo-Bot\pokemongo_bot\__init__.py", line 92, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "D:\Github\PokemonGo-Bot\pokemongo_bot\cell_workers\move_to_map_pokemon.py", line 161, in work
    self.update_map_location()
  File "D:\Github\PokemonGo-Bot\pokemongo_bot\cell_workers\move_to_map_pokemon.py", line 107, in update_map_location
    return log.logger('Map location data was not valid', 'red')
NameError: global name 'log' is not defined

Not sure how to troubleshoot it.

**Comment by wchill** [comment]
This repo will be replaced with a fresh rewrite as it's unmaintainable in its current state. (Just look how messy `main.js` is.)
